/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchoolIndexRouteImport } from './routes/school.index'
import { Route as SchoolProfileRouteImport } from './routes/school.profile'
import { Route as SchoolPreviewRouteImport } from './routes/school.preview'
import { Route as SchoolOnboardingRouteImport } from './routes/school.onboarding'
import { Route as SchoolApplicationsRouteImport } from './routes/school.applications'
import { Route as SchoolApplicationsIdRouteImport } from './routes/school.applications.$id'

const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolIndexRoute = SchoolIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolProfileRoute = SchoolProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolPreviewRoute = SchoolPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolOnboardingRoute = SchoolOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolApplicationsRoute = SchoolApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolApplicationsIdRoute = SchoolApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SchoolApplicationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/school': typeof SchoolRouteWithChildren
  '/school/applications': typeof SchoolApplicationsRouteWithChildren
  '/school/onboarding': typeof SchoolOnboardingRoute
  '/school/preview': typeof SchoolPreviewRoute
  '/school/profile': typeof SchoolProfileRoute
  '/school/': typeof SchoolIndexRoute
  '/school/applications/$id': typeof SchoolApplicationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/school/applications': typeof SchoolApplicationsRouteWithChildren
  '/school/onboarding': typeof SchoolOnboardingRoute
  '/school/preview': typeof SchoolPreviewRoute
  '/school/profile': typeof SchoolProfileRoute
  '/school': typeof SchoolIndexRoute
  '/school/applications/$id': typeof SchoolApplicationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/school': typeof SchoolRouteWithChildren
  '/school/applications': typeof SchoolApplicationsRouteWithChildren
  '/school/onboarding': typeof SchoolOnboardingRoute
  '/school/preview': typeof SchoolPreviewRoute
  '/school/profile': typeof SchoolProfileRoute
  '/school/': typeof SchoolIndexRoute
  '/school/applications/$id': typeof SchoolApplicationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/school'
    | '/school/applications'
    | '/school/onboarding'
    | '/school/preview'
    | '/school/profile'
    | '/school/'
    | '/school/applications/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/school/applications'
    | '/school/onboarding'
    | '/school/preview'
    | '/school/profile'
    | '/school'
    | '/school/applications/$id'
  id:
    | '__root__'
    | '/'
    | '/school'
    | '/school/applications'
    | '/school/onboarding'
    | '/school/preview'
    | '/school/profile'
    | '/school/'
    | '/school/applications/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SchoolRoute: typeof SchoolRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/': {
      id: '/school/'
      path: '/'
      fullPath: '/school/'
      preLoaderRoute: typeof SchoolIndexRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/profile': {
      id: '/school/profile'
      path: '/profile'
      fullPath: '/school/profile'
      preLoaderRoute: typeof SchoolProfileRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/preview': {
      id: '/school/preview'
      path: '/preview'
      fullPath: '/school/preview'
      preLoaderRoute: typeof SchoolPreviewRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/onboarding': {
      id: '/school/onboarding'
      path: '/onboarding'
      fullPath: '/school/onboarding'
      preLoaderRoute: typeof SchoolOnboardingRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/applications': {
      id: '/school/applications'
      path: '/applications'
      fullPath: '/school/applications'
      preLoaderRoute: typeof SchoolApplicationsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/applications/$id': {
      id: '/school/applications/$id'
      path: '/$id'
      fullPath: '/school/applications/$id'
      preLoaderRoute: typeof SchoolApplicationsIdRouteImport
      parentRoute: typeof SchoolApplicationsRoute
    }
  }
}

interface SchoolApplicationsRouteChildren {
  SchoolApplicationsIdRoute: typeof SchoolApplicationsIdRoute
}

const SchoolApplicationsRouteChildren: SchoolApplicationsRouteChildren = {
  SchoolApplicationsIdRoute: SchoolApplicationsIdRoute,
}

const SchoolApplicationsRouteWithChildren =
  SchoolApplicationsRoute._addFileChildren(SchoolApplicationsRouteChildren)

interface SchoolRouteChildren {
  SchoolApplicationsRoute: typeof SchoolApplicationsRouteWithChildren
  SchoolOnboardingRoute: typeof SchoolOnboardingRoute
  SchoolPreviewRoute: typeof SchoolPreviewRoute
  SchoolProfileRoute: typeof SchoolProfileRoute
  SchoolIndexRoute: typeof SchoolIndexRoute
}

const SchoolRouteChildren: SchoolRouteChildren = {
  SchoolApplicationsRoute: SchoolApplicationsRouteWithChildren,
  SchoolOnboardingRoute: SchoolOnboardingRoute,
  SchoolPreviewRoute: SchoolPreviewRoute,
  SchoolProfileRoute: SchoolProfileRoute,
  SchoolIndexRoute: SchoolIndexRoute,
}

const SchoolRouteWithChildren =
  SchoolRoute._addFileChildren(SchoolRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SchoolRoute: SchoolRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
