/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupplierRouteImport } from './routes/supplier'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplierIndexRouteImport } from './routes/supplier.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as SchoolsIndexRouteImport } from './routes/schools.index'
import { Route as SchoolIndexRouteImport } from './routes/school.index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as LogisticsIndexRouteImport } from './routes/logistics.index'
import { Route as SupplierWalletRouteImport } from './routes/supplier.wallet'
import { Route as SupplierSettingsRouteImport } from './routes/supplier.settings'
import { Route as SupplierSalesRouteImport } from './routes/supplier.sales'
import { Route as SupplierProductsRouteImport } from './routes/supplier.products'
import { Route as SupplierOrdersRouteImport } from './routes/supplier.orders'
import { Route as SupplierLogisticsRouteImport } from './routes/supplier.logistics'
import { Route as SupplierInventoryRouteImport } from './routes/supplier.inventory'
import { Route as StudentWalletRouteImport } from './routes/student.wallet'
import { Route as StudentUniformsRouteImport } from './routes/student.uniforms'
import { Route as StudentSchoolsRouteImport } from './routes/student.schools'
import { Route as StudentScholarshipsRouteImport } from './routes/student.scholarships'
import { Route as StudentReceiptsRouteImport } from './routes/student.receipts'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentPaymentsRouteImport } from './routes/student.payments'
import { Route as StudentOrdersRouteImport } from './routes/student.orders'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentFeesRouteImport } from './routes/student.fees'
import { Route as StudentDocumentsRouteImport } from './routes/student.documents'
import { Route as StudentApplicationsRouteImport } from './routes/student.applications'
import { Route as SchoolsIdRouteImport } from './routes/schools.$id'
import { Route as SchoolWalletRouteImport } from './routes/school.wallet'
import { Route as SchoolUniformsRouteImport } from './routes/school.uniforms'
import { Route as SchoolSuppliersRouteImport } from './routes/school.suppliers'
import { Route as SchoolSettingsRouteImport } from './routes/school.settings'
import { Route as SchoolRequirementsRouteImport } from './routes/school.requirements'
import { Route as SchoolReportsRouteImport } from './routes/school.reports'
import { Route as SchoolProfileRouteImport } from './routes/school.profile'
import { Route as SchoolPreviewRouteImport } from './routes/school.preview'
import { Route as SchoolPipelineRouteImport } from './routes/school.pipeline'
import { Route as SchoolPaymentsRouteImport } from './routes/school.payments'
import { Route as SchoolOnboardingRouteImport } from './routes/school.onboarding'
import { Route as SchoolGalleryRouteImport } from './routes/school.gallery'
import { Route as SchoolFeesRouteImport } from './routes/school.fees'
import { Route as SchoolClassesRouteImport } from './routes/school.classes'
import { Route as SchoolApplicationsRouteImport } from './routes/school.applications'
import { Route as ParentWalletRouteImport } from './routes/parent.wallet'
import { Route as ParentUniformsRouteImport } from './routes/parent.uniforms'
import { Route as ParentSettingsRouteImport } from './routes/parent.settings'
import { Route as ParentSchoolsRouteImport } from './routes/parent.schools'
import { Route as ParentScholarshipsRouteImport } from './routes/parent.scholarships'
import { Route as ParentReceiptsRouteImport } from './routes/parent.receipts'
import { Route as ParentPaymentsRouteImport } from './routes/parent.payments'
import { Route as ParentOrdersRouteImport } from './routes/parent.orders'
import { Route as ParentNotificationsRouteImport } from './routes/parent.notifications'
import { Route as ParentFeesRouteImport } from './routes/parent.fees'
import { Route as ParentDocumentsRouteImport } from './routes/parent.documents'
import { Route as ParentChildrenRouteImport } from './routes/parent.children'
import { Route as ParentApplyRouteImport } from './routes/parent.apply'
import { Route as ParentApplicationsRouteImport } from './routes/parent.applications'
import { Route as MarketplaceCheckoutRouteImport } from './routes/marketplace.checkout'
import { Route as MarketplaceCartRouteImport } from './routes/marketplace.cart'
import { Route as LogisticsWalletRouteImport } from './routes/logistics.wallet'
import { Route as LogisticsSettingsRouteImport } from './routes/logistics.settings'
import { Route as LogisticsRoutesRouteImport } from './routes/logistics.routes'
import { Route as LogisticsRegisterRouteImport } from './routes/logistics.register'
import { Route as LogisticsEarningsRouteImport } from './routes/logistics.earnings'
import { Route as LogisticsDeliveriesRouteImport } from './routes/logistics.deliveries'
import { Route as SupplierWalletDepositRouteImport } from './routes/supplier.wallet.deposit'
import { Route as SupplierProductsNewRouteImport } from './routes/supplier.products.new'
import { Route as SupplierOrdersIdRouteImport } from './routes/supplier.orders.$id'
import { Route as StudentWalletDepositRouteImport } from './routes/student.wallet.deposit'
import { Route as StudentScholarshipsSavedRouteImport } from './routes/student.scholarships.saved'
import { Route as StudentScholarshipsIdRouteImport } from './routes/student.scholarships.$id'
import { Route as StudentOrdersIdRouteImport } from './routes/student.orders.$id'
import { Route as SchoolWalletDepositRouteImport } from './routes/school.wallet.deposit'
import { Route as SchoolApplicationsIdRouteImport } from './routes/school.applications.$id'
import { Route as ParentWalletDepositRouteImport } from './routes/parent.wallet.deposit'
import { Route as ParentSchoolsIdRouteImport } from './routes/parent.schools.$id'
import { Route as ParentScholarshipsSavedRouteImport } from './routes/parent.scholarships.saved'
import { Route as ParentScholarshipsIdRouteImport } from './routes/parent.scholarships.$id'
import { Route as ParentReceiptsIdRouteImport } from './routes/parent.receipts.$id'
import { Route as ParentPaymentsPayRouteImport } from './routes/parent.payments.pay'
import { Route as ParentOrdersIdRouteImport } from './routes/parent.orders.$id'
import { Route as ParentChildrenNewRouteImport } from './routes/parent.children.new'
import { Route as ParentChildrenLinkRouteImport } from './routes/parent.children.link'
import { Route as ParentChildrenIdRouteImport } from './routes/parent.children.$id'
import { Route as ParentApplicationsIdRouteImport } from './routes/parent.applications.$id'
import { Route as MarketplaceProductsIdRouteImport } from './routes/marketplace.products.$id'
import { Route as LogisticsWalletDepositRouteImport } from './routes/logistics.wallet.deposit'
import { Route as LogisticsDeliveriesIdRouteImport } from './routes/logistics.deliveries.$id'

const SupplierRoute = SupplierRouteImport.update({
  id: '/supplier',
  path: '/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierIndexRoute = SupplierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupplierRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const SchoolsIndexRoute = SchoolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchoolsRoute,
} as any)
const SchoolIndexRoute = SchoolIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchoolRoute,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const LogisticsIndexRoute = LogisticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LogisticsRoute,
} as any)
const SupplierWalletRoute = SupplierWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierSettingsRoute = SupplierSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierSalesRoute = SupplierSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierProductsRoute = SupplierProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierOrdersRoute = SupplierOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierLogisticsRoute = SupplierLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierInventoryRoute = SupplierInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => SupplierRoute,
} as any)
const StudentWalletRoute = StudentWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => StudentRoute,
} as any)
const StudentUniformsRoute = StudentUniformsRouteImport.update({
  id: '/uniforms',
  path: '/uniforms',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSchoolsRoute = StudentSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => StudentRoute,
} as any)
const StudentScholarshipsRoute = StudentScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => StudentRoute,
} as any)
const StudentReceiptsRoute = StudentReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPaymentsRoute = StudentPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => StudentRoute,
} as any)
const StudentOrdersRoute = StudentOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFeesRoute = StudentFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDocumentsRoute = StudentDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => StudentRoute,
} as any)
const StudentApplicationsRoute = StudentApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => StudentRoute,
} as any)
const SchoolsIdRoute = SchoolsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SchoolsRoute,
} as any)
const SchoolWalletRoute = SchoolWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolUniformsRoute = SchoolUniformsRouteImport.update({
  id: '/uniforms',
  path: '/uniforms',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolSuppliersRoute = SchoolSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolSettingsRoute = SchoolSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolRequirementsRoute = SchoolRequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolReportsRoute = SchoolReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolProfileRoute = SchoolProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolPreviewRoute = SchoolPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolPipelineRoute = SchoolPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolPaymentsRoute = SchoolPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolOnboardingRoute = SchoolOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolGalleryRoute = SchoolGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolFeesRoute = SchoolFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolClassesRoute = SchoolClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => SchoolRoute,
} as any)
const SchoolApplicationsRoute = SchoolApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => SchoolRoute,
} as any)
const ParentWalletRoute = ParentWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => ParentRoute,
} as any)
const ParentUniformsRoute = ParentUniformsRouteImport.update({
  id: '/uniforms',
  path: '/uniforms',
  getParentRoute: () => ParentRoute,
} as any)
const ParentSettingsRoute = ParentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ParentRoute,
} as any)
const ParentSchoolsRoute = ParentSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => ParentRoute,
} as any)
const ParentScholarshipsRoute = ParentScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => ParentRoute,
} as any)
const ParentReceiptsRoute = ParentReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => ParentRoute,
} as any)
const ParentPaymentsRoute = ParentPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => ParentRoute,
} as any)
const ParentOrdersRoute = ParentOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => ParentRoute,
} as any)
const ParentNotificationsRoute = ParentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ParentRoute,
} as any)
const ParentFeesRoute = ParentFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => ParentRoute,
} as any)
const ParentDocumentsRoute = ParentDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ParentRoute,
} as any)
const ParentChildrenRoute = ParentChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => ParentRoute,
} as any)
const ParentApplyRoute = ParentApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => ParentRoute,
} as any)
const ParentApplicationsRoute = ParentApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => ParentRoute,
} as any)
const MarketplaceCheckoutRoute = MarketplaceCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceCartRoute = MarketplaceCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => MarketplaceRoute,
} as any)
const LogisticsWalletRoute = LogisticsWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => LogisticsRoute,
} as any)
const LogisticsSettingsRoute = LogisticsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LogisticsRoute,
} as any)
const LogisticsRoutesRoute = LogisticsRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => LogisticsRoute,
} as any)
const LogisticsRegisterRoute = LogisticsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LogisticsRoute,
} as any)
const LogisticsEarningsRoute = LogisticsEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => LogisticsRoute,
} as any)
const LogisticsDeliveriesRoute = LogisticsDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => LogisticsRoute,
} as any)
const SupplierWalletDepositRoute = SupplierWalletDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => SupplierWalletRoute,
} as any)
const SupplierProductsNewRoute = SupplierProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SupplierProductsRoute,
} as any)
const SupplierOrdersIdRoute = SupplierOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SupplierOrdersRoute,
} as any)
const StudentWalletDepositRoute = StudentWalletDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => StudentWalletRoute,
} as any)
const StudentScholarshipsSavedRoute =
  StudentScholarshipsSavedRouteImport.update({
    id: '/saved',
    path: '/saved',
    getParentRoute: () => StudentScholarshipsRoute,
  } as any)
const StudentScholarshipsIdRoute = StudentScholarshipsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentScholarshipsRoute,
} as any)
const StudentOrdersIdRoute = StudentOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentOrdersRoute,
} as any)
const SchoolWalletDepositRoute = SchoolWalletDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => SchoolWalletRoute,
} as any)
const SchoolApplicationsIdRoute = SchoolApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SchoolApplicationsRoute,
} as any)
const ParentWalletDepositRoute = ParentWalletDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => ParentWalletRoute,
} as any)
const ParentSchoolsIdRoute = ParentSchoolsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ParentSchoolsRoute,
} as any)
const ParentScholarshipsSavedRoute = ParentScholarshipsSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => ParentScholarshipsRoute,
} as any)
const ParentScholarshipsIdRoute = ParentScholarshipsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ParentScholarshipsRoute,
} as any)
const ParentReceiptsIdRoute = ParentReceiptsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ParentReceiptsRoute,
} as any)
const ParentPaymentsPayRoute = ParentPaymentsPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => ParentPaymentsRoute,
} as any)
const ParentOrdersIdRoute = ParentOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ParentOrdersRoute,
} as any)
const ParentChildrenNewRoute = ParentChildrenNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ParentChildrenRoute,
} as any)
const ParentChildrenLinkRoute = ParentChildrenLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => ParentChildrenRoute,
} as any)
const ParentChildrenIdRoute = ParentChildrenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ParentChildrenRoute,
} as any)
const ParentApplicationsIdRoute = ParentApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ParentApplicationsRoute,
} as any)
const MarketplaceProductsIdRoute = MarketplaceProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => MarketplaceRoute,
} as any)
const LogisticsWalletDepositRoute = LogisticsWalletDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => LogisticsWalletRoute,
} as any)
const LogisticsDeliveriesIdRoute = LogisticsDeliveriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LogisticsDeliveriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/register': typeof RegisterRoute
  '/school': typeof SchoolRouteWithChildren
  '/schools': typeof SchoolsRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/supplier': typeof SupplierRouteWithChildren
  '/logistics/deliveries': typeof LogisticsDeliveriesRouteWithChildren
  '/logistics/earnings': typeof LogisticsEarningsRoute
  '/logistics/register': typeof LogisticsRegisterRoute
  '/logistics/routes': typeof LogisticsRoutesRoute
  '/logistics/settings': typeof LogisticsSettingsRoute
  '/logistics/wallet': typeof LogisticsWalletRouteWithChildren
  '/marketplace/cart': typeof MarketplaceCartRoute
  '/marketplace/checkout': typeof MarketplaceCheckoutRoute
  '/parent/applications': typeof ParentApplicationsRouteWithChildren
  '/parent/apply': typeof ParentApplyRoute
  '/parent/children': typeof ParentChildrenRouteWithChildren
  '/parent/documents': typeof ParentDocumentsRoute
  '/parent/fees': typeof ParentFeesRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/orders': typeof ParentOrdersRouteWithChildren
  '/parent/payments': typeof ParentPaymentsRouteWithChildren
  '/parent/receipts': typeof ParentReceiptsRouteWithChildren
  '/parent/scholarships': typeof ParentScholarshipsRouteWithChildren
  '/parent/schools': typeof ParentSchoolsRouteWithChildren
  '/parent/settings': typeof ParentSettingsRoute
  '/parent/uniforms': typeof ParentUniformsRoute
  '/parent/wallet': typeof ParentWalletRouteWithChildren
  '/school/applications': typeof SchoolApplicationsRouteWithChildren
  '/school/classes': typeof SchoolClassesRoute
  '/school/fees': typeof SchoolFeesRoute
  '/school/gallery': typeof SchoolGalleryRoute
  '/school/onboarding': typeof SchoolOnboardingRoute
  '/school/payments': typeof SchoolPaymentsRoute
  '/school/pipeline': typeof SchoolPipelineRoute
  '/school/preview': typeof SchoolPreviewRoute
  '/school/profile': typeof SchoolProfileRoute
  '/school/reports': typeof SchoolReportsRoute
  '/school/requirements': typeof SchoolRequirementsRoute
  '/school/settings': typeof SchoolSettingsRoute
  '/school/suppliers': typeof SchoolSuppliersRoute
  '/school/uniforms': typeof SchoolUniformsRoute
  '/school/wallet': typeof SchoolWalletRouteWithChildren
  '/schools/$id': typeof SchoolsIdRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/documents': typeof StudentDocumentsRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/orders': typeof StudentOrdersRouteWithChildren
  '/student/payments': typeof StudentPaymentsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/receipts': typeof StudentReceiptsRoute
  '/student/scholarships': typeof StudentScholarshipsRouteWithChildren
  '/student/schools': typeof StudentSchoolsRoute
  '/student/uniforms': typeof StudentUniformsRoute
  '/student/wallet': typeof StudentWalletRouteWithChildren
  '/supplier/inventory': typeof SupplierInventoryRoute
  '/supplier/logistics': typeof SupplierLogisticsRoute
  '/supplier/orders': typeof SupplierOrdersRouteWithChildren
  '/supplier/products': typeof SupplierProductsRouteWithChildren
  '/supplier/sales': typeof SupplierSalesRoute
  '/supplier/settings': typeof SupplierSettingsRoute
  '/supplier/wallet': typeof SupplierWalletRouteWithChildren
  '/logistics/': typeof LogisticsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/school/': typeof SchoolIndexRoute
  '/schools/': typeof SchoolsIndexRoute
  '/student/': typeof StudentIndexRoute
  '/supplier/': typeof SupplierIndexRoute
  '/logistics/deliveries/$id': typeof LogisticsDeliveriesIdRoute
  '/logistics/wallet/deposit': typeof LogisticsWalletDepositRoute
  '/marketplace/products/$id': typeof MarketplaceProductsIdRoute
  '/parent/applications/$id': typeof ParentApplicationsIdRoute
  '/parent/children/$id': typeof ParentChildrenIdRoute
  '/parent/children/link': typeof ParentChildrenLinkRoute
  '/parent/children/new': typeof ParentChildrenNewRoute
  '/parent/orders/$id': typeof ParentOrdersIdRoute
  '/parent/payments/pay': typeof ParentPaymentsPayRoute
  '/parent/receipts/$id': typeof ParentReceiptsIdRoute
  '/parent/scholarships/$id': typeof ParentScholarshipsIdRoute
  '/parent/scholarships/saved': typeof ParentScholarshipsSavedRoute
  '/parent/schools/$id': typeof ParentSchoolsIdRoute
  '/parent/wallet/deposit': typeof ParentWalletDepositRoute
  '/school/applications/$id': typeof SchoolApplicationsIdRoute
  '/school/wallet/deposit': typeof SchoolWalletDepositRoute
  '/student/orders/$id': typeof StudentOrdersIdRoute
  '/student/scholarships/$id': typeof StudentScholarshipsIdRoute
  '/student/scholarships/saved': typeof StudentScholarshipsSavedRoute
  '/student/wallet/deposit': typeof StudentWalletDepositRoute
  '/supplier/orders/$id': typeof SupplierOrdersIdRoute
  '/supplier/products/new': typeof SupplierProductsNewRoute
  '/supplier/wallet/deposit': typeof SupplierWalletDepositRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/logistics/deliveries': typeof LogisticsDeliveriesRouteWithChildren
  '/logistics/earnings': typeof LogisticsEarningsRoute
  '/logistics/register': typeof LogisticsRegisterRoute
  '/logistics/routes': typeof LogisticsRoutesRoute
  '/logistics/settings': typeof LogisticsSettingsRoute
  '/logistics/wallet': typeof LogisticsWalletRouteWithChildren
  '/marketplace/cart': typeof MarketplaceCartRoute
  '/marketplace/checkout': typeof MarketplaceCheckoutRoute
  '/parent/applications': typeof ParentApplicationsRouteWithChildren
  '/parent/apply': typeof ParentApplyRoute
  '/parent/children': typeof ParentChildrenRouteWithChildren
  '/parent/documents': typeof ParentDocumentsRoute
  '/parent/fees': typeof ParentFeesRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/orders': typeof ParentOrdersRouteWithChildren
  '/parent/payments': typeof ParentPaymentsRouteWithChildren
  '/parent/receipts': typeof ParentReceiptsRouteWithChildren
  '/parent/scholarships': typeof ParentScholarshipsRouteWithChildren
  '/parent/schools': typeof ParentSchoolsRouteWithChildren
  '/parent/settings': typeof ParentSettingsRoute
  '/parent/uniforms': typeof ParentUniformsRoute
  '/parent/wallet': typeof ParentWalletRouteWithChildren
  '/school/applications': typeof SchoolApplicationsRouteWithChildren
  '/school/classes': typeof SchoolClassesRoute
  '/school/fees': typeof SchoolFeesRoute
  '/school/gallery': typeof SchoolGalleryRoute
  '/school/onboarding': typeof SchoolOnboardingRoute
  '/school/payments': typeof SchoolPaymentsRoute
  '/school/pipeline': typeof SchoolPipelineRoute
  '/school/preview': typeof SchoolPreviewRoute
  '/school/profile': typeof SchoolProfileRoute
  '/school/reports': typeof SchoolReportsRoute
  '/school/requirements': typeof SchoolRequirementsRoute
  '/school/settings': typeof SchoolSettingsRoute
  '/school/suppliers': typeof SchoolSuppliersRoute
  '/school/uniforms': typeof SchoolUniformsRoute
  '/school/wallet': typeof SchoolWalletRouteWithChildren
  '/schools/$id': typeof SchoolsIdRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/documents': typeof StudentDocumentsRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/orders': typeof StudentOrdersRouteWithChildren
  '/student/payments': typeof StudentPaymentsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/receipts': typeof StudentReceiptsRoute
  '/student/scholarships': typeof StudentScholarshipsRouteWithChildren
  '/student/schools': typeof StudentSchoolsRoute
  '/student/uniforms': typeof StudentUniformsRoute
  '/student/wallet': typeof StudentWalletRouteWithChildren
  '/supplier/inventory': typeof SupplierInventoryRoute
  '/supplier/logistics': typeof SupplierLogisticsRoute
  '/supplier/orders': typeof SupplierOrdersRouteWithChildren
  '/supplier/products': typeof SupplierProductsRouteWithChildren
  '/supplier/sales': typeof SupplierSalesRoute
  '/supplier/settings': typeof SupplierSettingsRoute
  '/supplier/wallet': typeof SupplierWalletRouteWithChildren
  '/logistics': typeof LogisticsIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/parent': typeof ParentIndexRoute
  '/school': typeof SchoolIndexRoute
  '/schools': typeof SchoolsIndexRoute
  '/student': typeof StudentIndexRoute
  '/supplier': typeof SupplierIndexRoute
  '/logistics/deliveries/$id': typeof LogisticsDeliveriesIdRoute
  '/logistics/wallet/deposit': typeof LogisticsWalletDepositRoute
  '/marketplace/products/$id': typeof MarketplaceProductsIdRoute
  '/parent/applications/$id': typeof ParentApplicationsIdRoute
  '/parent/children/$id': typeof ParentChildrenIdRoute
  '/parent/children/link': typeof ParentChildrenLinkRoute
  '/parent/children/new': typeof ParentChildrenNewRoute
  '/parent/orders/$id': typeof ParentOrdersIdRoute
  '/parent/payments/pay': typeof ParentPaymentsPayRoute
  '/parent/receipts/$id': typeof ParentReceiptsIdRoute
  '/parent/scholarships/$id': typeof ParentScholarshipsIdRoute
  '/parent/scholarships/saved': typeof ParentScholarshipsSavedRoute
  '/parent/schools/$id': typeof ParentSchoolsIdRoute
  '/parent/wallet/deposit': typeof ParentWalletDepositRoute
  '/school/applications/$id': typeof SchoolApplicationsIdRoute
  '/school/wallet/deposit': typeof SchoolWalletDepositRoute
  '/student/orders/$id': typeof StudentOrdersIdRoute
  '/student/scholarships/$id': typeof StudentScholarshipsIdRoute
  '/student/scholarships/saved': typeof StudentScholarshipsSavedRoute
  '/student/wallet/deposit': typeof StudentWalletDepositRoute
  '/supplier/orders/$id': typeof SupplierOrdersIdRoute
  '/supplier/products/new': typeof SupplierProductsNewRoute
  '/supplier/wallet/deposit': typeof SupplierWalletDepositRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/logistics': typeof LogisticsRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/register': typeof RegisterRoute
  '/school': typeof SchoolRouteWithChildren
  '/schools': typeof SchoolsRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/supplier': typeof SupplierRouteWithChildren
  '/logistics/deliveries': typeof LogisticsDeliveriesRouteWithChildren
  '/logistics/earnings': typeof LogisticsEarningsRoute
  '/logistics/register': typeof LogisticsRegisterRoute
  '/logistics/routes': typeof LogisticsRoutesRoute
  '/logistics/settings': typeof LogisticsSettingsRoute
  '/logistics/wallet': typeof LogisticsWalletRouteWithChildren
  '/marketplace/cart': typeof MarketplaceCartRoute
  '/marketplace/checkout': typeof MarketplaceCheckoutRoute
  '/parent/applications': typeof ParentApplicationsRouteWithChildren
  '/parent/apply': typeof ParentApplyRoute
  '/parent/children': typeof ParentChildrenRouteWithChildren
  '/parent/documents': typeof ParentDocumentsRoute
  '/parent/fees': typeof ParentFeesRoute
  '/parent/notifications': typeof ParentNotificationsRoute
  '/parent/orders': typeof ParentOrdersRouteWithChildren
  '/parent/payments': typeof ParentPaymentsRouteWithChildren
  '/parent/receipts': typeof ParentReceiptsRouteWithChildren
  '/parent/scholarships': typeof ParentScholarshipsRouteWithChildren
  '/parent/schools': typeof ParentSchoolsRouteWithChildren
  '/parent/settings': typeof ParentSettingsRoute
  '/parent/uniforms': typeof ParentUniformsRoute
  '/parent/wallet': typeof ParentWalletRouteWithChildren
  '/school/applications': typeof SchoolApplicationsRouteWithChildren
  '/school/classes': typeof SchoolClassesRoute
  '/school/fees': typeof SchoolFeesRoute
  '/school/gallery': typeof SchoolGalleryRoute
  '/school/onboarding': typeof SchoolOnboardingRoute
  '/school/payments': typeof SchoolPaymentsRoute
  '/school/pipeline': typeof SchoolPipelineRoute
  '/school/preview': typeof SchoolPreviewRoute
  '/school/profile': typeof SchoolProfileRoute
  '/school/reports': typeof SchoolReportsRoute
  '/school/requirements': typeof SchoolRequirementsRoute
  '/school/settings': typeof SchoolSettingsRoute
  '/school/suppliers': typeof SchoolSuppliersRoute
  '/school/uniforms': typeof SchoolUniformsRoute
  '/school/wallet': typeof SchoolWalletRouteWithChildren
  '/schools/$id': typeof SchoolsIdRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/documents': typeof StudentDocumentsRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/orders': typeof StudentOrdersRouteWithChildren
  '/student/payments': typeof StudentPaymentsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/receipts': typeof StudentReceiptsRoute
  '/student/scholarships': typeof StudentScholarshipsRouteWithChildren
  '/student/schools': typeof StudentSchoolsRoute
  '/student/uniforms': typeof StudentUniformsRoute
  '/student/wallet': typeof StudentWalletRouteWithChildren
  '/supplier/inventory': typeof SupplierInventoryRoute
  '/supplier/logistics': typeof SupplierLogisticsRoute
  '/supplier/orders': typeof SupplierOrdersRouteWithChildren
  '/supplier/products': typeof SupplierProductsRouteWithChildren
  '/supplier/sales': typeof SupplierSalesRoute
  '/supplier/settings': typeof SupplierSettingsRoute
  '/supplier/wallet': typeof SupplierWalletRouteWithChildren
  '/logistics/': typeof LogisticsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/school/': typeof SchoolIndexRoute
  '/schools/': typeof SchoolsIndexRoute
  '/student/': typeof StudentIndexRoute
  '/supplier/': typeof SupplierIndexRoute
  '/logistics/deliveries/$id': typeof LogisticsDeliveriesIdRoute
  '/logistics/wallet/deposit': typeof LogisticsWalletDepositRoute
  '/marketplace/products/$id': typeof MarketplaceProductsIdRoute
  '/parent/applications/$id': typeof ParentApplicationsIdRoute
  '/parent/children/$id': typeof ParentChildrenIdRoute
  '/parent/children/link': typeof ParentChildrenLinkRoute
  '/parent/children/new': typeof ParentChildrenNewRoute
  '/parent/orders/$id': typeof ParentOrdersIdRoute
  '/parent/payments/pay': typeof ParentPaymentsPayRoute
  '/parent/receipts/$id': typeof ParentReceiptsIdRoute
  '/parent/scholarships/$id': typeof ParentScholarshipsIdRoute
  '/parent/scholarships/saved': typeof ParentScholarshipsSavedRoute
  '/parent/schools/$id': typeof ParentSchoolsIdRoute
  '/parent/wallet/deposit': typeof ParentWalletDepositRoute
  '/school/applications/$id': typeof SchoolApplicationsIdRoute
  '/school/wallet/deposit': typeof SchoolWalletDepositRoute
  '/student/orders/$id': typeof StudentOrdersIdRoute
  '/student/scholarships/$id': typeof StudentScholarshipsIdRoute
  '/student/scholarships/saved': typeof StudentScholarshipsSavedRoute
  '/student/wallet/deposit': typeof StudentWalletDepositRoute
  '/supplier/orders/$id': typeof SupplierOrdersIdRoute
  '/supplier/products/new': typeof SupplierProductsNewRoute
  '/supplier/wallet/deposit': typeof SupplierWalletDepositRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/get-started'
    | '/login'
    | '/logistics'
    | '/marketplace'
    | '/parent'
    | '/register'
    | '/school'
    | '/schools'
    | '/student'
    | '/supplier'
    | '/logistics/deliveries'
    | '/logistics/earnings'
    | '/logistics/register'
    | '/logistics/routes'
    | '/logistics/settings'
    | '/logistics/wallet'
    | '/marketplace/cart'
    | '/marketplace/checkout'
    | '/parent/applications'
    | '/parent/apply'
    | '/parent/children'
    | '/parent/documents'
    | '/parent/fees'
    | '/parent/notifications'
    | '/parent/orders'
    | '/parent/payments'
    | '/parent/receipts'
    | '/parent/scholarships'
    | '/parent/schools'
    | '/parent/settings'
    | '/parent/uniforms'
    | '/parent/wallet'
    | '/school/applications'
    | '/school/classes'
    | '/school/fees'
    | '/school/gallery'
    | '/school/onboarding'
    | '/school/payments'
    | '/school/pipeline'
    | '/school/preview'
    | '/school/profile'
    | '/school/reports'
    | '/school/requirements'
    | '/school/settings'
    | '/school/suppliers'
    | '/school/uniforms'
    | '/school/wallet'
    | '/schools/$id'
    | '/student/applications'
    | '/student/documents'
    | '/student/fees'
    | '/student/notifications'
    | '/student/orders'
    | '/student/payments'
    | '/student/profile'
    | '/student/receipts'
    | '/student/scholarships'
    | '/student/schools'
    | '/student/uniforms'
    | '/student/wallet'
    | '/supplier/inventory'
    | '/supplier/logistics'
    | '/supplier/orders'
    | '/supplier/products'
    | '/supplier/sales'
    | '/supplier/settings'
    | '/supplier/wallet'
    | '/logistics/'
    | '/marketplace/'
    | '/parent/'
    | '/school/'
    | '/schools/'
    | '/student/'
    | '/supplier/'
    | '/logistics/deliveries/$id'
    | '/logistics/wallet/deposit'
    | '/marketplace/products/$id'
    | '/parent/applications/$id'
    | '/parent/children/$id'
    | '/parent/children/link'
    | '/parent/children/new'
    | '/parent/orders/$id'
    | '/parent/payments/pay'
    | '/parent/receipts/$id'
    | '/parent/scholarships/$id'
    | '/parent/scholarships/saved'
    | '/parent/schools/$id'
    | '/parent/wallet/deposit'
    | '/school/applications/$id'
    | '/school/wallet/deposit'
    | '/student/orders/$id'
    | '/student/scholarships/$id'
    | '/student/scholarships/saved'
    | '/student/wallet/deposit'
    | '/supplier/orders/$id'
    | '/supplier/products/new'
    | '/supplier/wallet/deposit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get-started'
    | '/login'
    | '/register'
    | '/logistics/deliveries'
    | '/logistics/earnings'
    | '/logistics/register'
    | '/logistics/routes'
    | '/logistics/settings'
    | '/logistics/wallet'
    | '/marketplace/cart'
    | '/marketplace/checkout'
    | '/parent/applications'
    | '/parent/apply'
    | '/parent/children'
    | '/parent/documents'
    | '/parent/fees'
    | '/parent/notifications'
    | '/parent/orders'
    | '/parent/payments'
    | '/parent/receipts'
    | '/parent/scholarships'
    | '/parent/schools'
    | '/parent/settings'
    | '/parent/uniforms'
    | '/parent/wallet'
    | '/school/applications'
    | '/school/classes'
    | '/school/fees'
    | '/school/gallery'
    | '/school/onboarding'
    | '/school/payments'
    | '/school/pipeline'
    | '/school/preview'
    | '/school/profile'
    | '/school/reports'
    | '/school/requirements'
    | '/school/settings'
    | '/school/suppliers'
    | '/school/uniforms'
    | '/school/wallet'
    | '/schools/$id'
    | '/student/applications'
    | '/student/documents'
    | '/student/fees'
    | '/student/notifications'
    | '/student/orders'
    | '/student/payments'
    | '/student/profile'
    | '/student/receipts'
    | '/student/scholarships'
    | '/student/schools'
    | '/student/uniforms'
    | '/student/wallet'
    | '/supplier/inventory'
    | '/supplier/logistics'
    | '/supplier/orders'
    | '/supplier/products'
    | '/supplier/sales'
    | '/supplier/settings'
    | '/supplier/wallet'
    | '/logistics'
    | '/marketplace'
    | '/parent'
    | '/school'
    | '/schools'
    | '/student'
    | '/supplier'
    | '/logistics/deliveries/$id'
    | '/logistics/wallet/deposit'
    | '/marketplace/products/$id'
    | '/parent/applications/$id'
    | '/parent/children/$id'
    | '/parent/children/link'
    | '/parent/children/new'
    | '/parent/orders/$id'
    | '/parent/payments/pay'
    | '/parent/receipts/$id'
    | '/parent/scholarships/$id'
    | '/parent/scholarships/saved'
    | '/parent/schools/$id'
    | '/parent/wallet/deposit'
    | '/school/applications/$id'
    | '/school/wallet/deposit'
    | '/student/orders/$id'
    | '/student/scholarships/$id'
    | '/student/scholarships/saved'
    | '/student/wallet/deposit'
    | '/supplier/orders/$id'
    | '/supplier/products/new'
    | '/supplier/wallet/deposit'
  id:
    | '__root__'
    | '/'
    | '/get-started'
    | '/login'
    | '/logistics'
    | '/marketplace'
    | '/parent'
    | '/register'
    | '/school'
    | '/schools'
    | '/student'
    | '/supplier'
    | '/logistics/deliveries'
    | '/logistics/earnings'
    | '/logistics/register'
    | '/logistics/routes'
    | '/logistics/settings'
    | '/logistics/wallet'
    | '/marketplace/cart'
    | '/marketplace/checkout'
    | '/parent/applications'
    | '/parent/apply'
    | '/parent/children'
    | '/parent/documents'
    | '/parent/fees'
    | '/parent/notifications'
    | '/parent/orders'
    | '/parent/payments'
    | '/parent/receipts'
    | '/parent/scholarships'
    | '/parent/schools'
    | '/parent/settings'
    | '/parent/uniforms'
    | '/parent/wallet'
    | '/school/applications'
    | '/school/classes'
    | '/school/fees'
    | '/school/gallery'
    | '/school/onboarding'
    | '/school/payments'
    | '/school/pipeline'
    | '/school/preview'
    | '/school/profile'
    | '/school/reports'
    | '/school/requirements'
    | '/school/settings'
    | '/school/suppliers'
    | '/school/uniforms'
    | '/school/wallet'
    | '/schools/$id'
    | '/student/applications'
    | '/student/documents'
    | '/student/fees'
    | '/student/notifications'
    | '/student/orders'
    | '/student/payments'
    | '/student/profile'
    | '/student/receipts'
    | '/student/scholarships'
    | '/student/schools'
    | '/student/uniforms'
    | '/student/wallet'
    | '/supplier/inventory'
    | '/supplier/logistics'
    | '/supplier/orders'
    | '/supplier/products'
    | '/supplier/sales'
    | '/supplier/settings'
    | '/supplier/wallet'
    | '/logistics/'
    | '/marketplace/'
    | '/parent/'
    | '/school/'
    | '/schools/'
    | '/student/'
    | '/supplier/'
    | '/logistics/deliveries/$id'
    | '/logistics/wallet/deposit'
    | '/marketplace/products/$id'
    | '/parent/applications/$id'
    | '/parent/children/$id'
    | '/parent/children/link'
    | '/parent/children/new'
    | '/parent/orders/$id'
    | '/parent/payments/pay'
    | '/parent/receipts/$id'
    | '/parent/scholarships/$id'
    | '/parent/scholarships/saved'
    | '/parent/schools/$id'
    | '/parent/wallet/deposit'
    | '/school/applications/$id'
    | '/school/wallet/deposit'
    | '/student/orders/$id'
    | '/student/scholarships/$id'
    | '/student/scholarships/saved'
    | '/student/wallet/deposit'
    | '/supplier/orders/$id'
    | '/supplier/products/new'
    | '/supplier/wallet/deposit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GetStartedRoute: typeof GetStartedRoute
  LoginRoute: typeof LoginRoute
  LogisticsRoute: typeof LogisticsRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  ParentRoute: typeof ParentRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SchoolRoute: typeof SchoolRouteWithChildren
  SchoolsRoute: typeof SchoolsRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  SupplierRoute: typeof SupplierRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supplier': {
      id: '/supplier'
      path: '/supplier'
      fullPath: '/supplier'
      preLoaderRoute: typeof SupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/': {
      id: '/supplier/'
      path: '/'
      fullPath: '/supplier/'
      preLoaderRoute: typeof SupplierIndexRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/schools/': {
      id: '/schools/'
      path: '/'
      fullPath: '/schools/'
      preLoaderRoute: typeof SchoolsIndexRouteImport
      parentRoute: typeof SchoolsRoute
    }
    '/school/': {
      id: '/school/'
      path: '/'
      fullPath: '/school/'
      preLoaderRoute: typeof SchoolIndexRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/logistics/': {
      id: '/logistics/'
      path: '/'
      fullPath: '/logistics/'
      preLoaderRoute: typeof LogisticsIndexRouteImport
      parentRoute: typeof LogisticsRoute
    }
    '/supplier/wallet': {
      id: '/supplier/wallet'
      path: '/wallet'
      fullPath: '/supplier/wallet'
      preLoaderRoute: typeof SupplierWalletRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/settings': {
      id: '/supplier/settings'
      path: '/settings'
      fullPath: '/supplier/settings'
      preLoaderRoute: typeof SupplierSettingsRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/sales': {
      id: '/supplier/sales'
      path: '/sales'
      fullPath: '/supplier/sales'
      preLoaderRoute: typeof SupplierSalesRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/products': {
      id: '/supplier/products'
      path: '/products'
      fullPath: '/supplier/products'
      preLoaderRoute: typeof SupplierProductsRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/orders': {
      id: '/supplier/orders'
      path: '/orders'
      fullPath: '/supplier/orders'
      preLoaderRoute: typeof SupplierOrdersRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/logistics': {
      id: '/supplier/logistics'
      path: '/logistics'
      fullPath: '/supplier/logistics'
      preLoaderRoute: typeof SupplierLogisticsRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/inventory': {
      id: '/supplier/inventory'
      path: '/inventory'
      fullPath: '/supplier/inventory'
      preLoaderRoute: typeof SupplierInventoryRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/student/wallet': {
      id: '/student/wallet'
      path: '/wallet'
      fullPath: '/student/wallet'
      preLoaderRoute: typeof StudentWalletRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/uniforms': {
      id: '/student/uniforms'
      path: '/uniforms'
      fullPath: '/student/uniforms'
      preLoaderRoute: typeof StudentUniformsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/schools': {
      id: '/student/schools'
      path: '/schools'
      fullPath: '/student/schools'
      preLoaderRoute: typeof StudentSchoolsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/scholarships': {
      id: '/student/scholarships'
      path: '/scholarships'
      fullPath: '/student/scholarships'
      preLoaderRoute: typeof StudentScholarshipsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/receipts': {
      id: '/student/receipts'
      path: '/receipts'
      fullPath: '/student/receipts'
      preLoaderRoute: typeof StudentReceiptsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/payments': {
      id: '/student/payments'
      path: '/payments'
      fullPath: '/student/payments'
      preLoaderRoute: typeof StudentPaymentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/orders': {
      id: '/student/orders'
      path: '/orders'
      fullPath: '/student/orders'
      preLoaderRoute: typeof StudentOrdersRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/fees': {
      id: '/student/fees'
      path: '/fees'
      fullPath: '/student/fees'
      preLoaderRoute: typeof StudentFeesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/documents': {
      id: '/student/documents'
      path: '/documents'
      fullPath: '/student/documents'
      preLoaderRoute: typeof StudentDocumentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/applications': {
      id: '/student/applications'
      path: '/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof StudentApplicationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/schools/$id': {
      id: '/schools/$id'
      path: '/$id'
      fullPath: '/schools/$id'
      preLoaderRoute: typeof SchoolsIdRouteImport
      parentRoute: typeof SchoolsRoute
    }
    '/school/wallet': {
      id: '/school/wallet'
      path: '/wallet'
      fullPath: '/school/wallet'
      preLoaderRoute: typeof SchoolWalletRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/uniforms': {
      id: '/school/uniforms'
      path: '/uniforms'
      fullPath: '/school/uniforms'
      preLoaderRoute: typeof SchoolUniformsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/suppliers': {
      id: '/school/suppliers'
      path: '/suppliers'
      fullPath: '/school/suppliers'
      preLoaderRoute: typeof SchoolSuppliersRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/settings': {
      id: '/school/settings'
      path: '/settings'
      fullPath: '/school/settings'
      preLoaderRoute: typeof SchoolSettingsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/requirements': {
      id: '/school/requirements'
      path: '/requirements'
      fullPath: '/school/requirements'
      preLoaderRoute: typeof SchoolRequirementsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/reports': {
      id: '/school/reports'
      path: '/reports'
      fullPath: '/school/reports'
      preLoaderRoute: typeof SchoolReportsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/profile': {
      id: '/school/profile'
      path: '/profile'
      fullPath: '/school/profile'
      preLoaderRoute: typeof SchoolProfileRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/preview': {
      id: '/school/preview'
      path: '/preview'
      fullPath: '/school/preview'
      preLoaderRoute: typeof SchoolPreviewRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/pipeline': {
      id: '/school/pipeline'
      path: '/pipeline'
      fullPath: '/school/pipeline'
      preLoaderRoute: typeof SchoolPipelineRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/payments': {
      id: '/school/payments'
      path: '/payments'
      fullPath: '/school/payments'
      preLoaderRoute: typeof SchoolPaymentsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/onboarding': {
      id: '/school/onboarding'
      path: '/onboarding'
      fullPath: '/school/onboarding'
      preLoaderRoute: typeof SchoolOnboardingRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/gallery': {
      id: '/school/gallery'
      path: '/gallery'
      fullPath: '/school/gallery'
      preLoaderRoute: typeof SchoolGalleryRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/fees': {
      id: '/school/fees'
      path: '/fees'
      fullPath: '/school/fees'
      preLoaderRoute: typeof SchoolFeesRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/classes': {
      id: '/school/classes'
      path: '/classes'
      fullPath: '/school/classes'
      preLoaderRoute: typeof SchoolClassesRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/school/applications': {
      id: '/school/applications'
      path: '/applications'
      fullPath: '/school/applications'
      preLoaderRoute: typeof SchoolApplicationsRouteImport
      parentRoute: typeof SchoolRoute
    }
    '/parent/wallet': {
      id: '/parent/wallet'
      path: '/wallet'
      fullPath: '/parent/wallet'
      preLoaderRoute: typeof ParentWalletRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/uniforms': {
      id: '/parent/uniforms'
      path: '/uniforms'
      fullPath: '/parent/uniforms'
      preLoaderRoute: typeof ParentUniformsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/settings': {
      id: '/parent/settings'
      path: '/settings'
      fullPath: '/parent/settings'
      preLoaderRoute: typeof ParentSettingsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/schools': {
      id: '/parent/schools'
      path: '/schools'
      fullPath: '/parent/schools'
      preLoaderRoute: typeof ParentSchoolsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/scholarships': {
      id: '/parent/scholarships'
      path: '/scholarships'
      fullPath: '/parent/scholarships'
      preLoaderRoute: typeof ParentScholarshipsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/receipts': {
      id: '/parent/receipts'
      path: '/receipts'
      fullPath: '/parent/receipts'
      preLoaderRoute: typeof ParentReceiptsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/payments': {
      id: '/parent/payments'
      path: '/payments'
      fullPath: '/parent/payments'
      preLoaderRoute: typeof ParentPaymentsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/orders': {
      id: '/parent/orders'
      path: '/orders'
      fullPath: '/parent/orders'
      preLoaderRoute: typeof ParentOrdersRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/notifications': {
      id: '/parent/notifications'
      path: '/notifications'
      fullPath: '/parent/notifications'
      preLoaderRoute: typeof ParentNotificationsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/fees': {
      id: '/parent/fees'
      path: '/fees'
      fullPath: '/parent/fees'
      preLoaderRoute: typeof ParentFeesRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/documents': {
      id: '/parent/documents'
      path: '/documents'
      fullPath: '/parent/documents'
      preLoaderRoute: typeof ParentDocumentsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/children': {
      id: '/parent/children'
      path: '/children'
      fullPath: '/parent/children'
      preLoaderRoute: typeof ParentChildrenRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/apply': {
      id: '/parent/apply'
      path: '/apply'
      fullPath: '/parent/apply'
      preLoaderRoute: typeof ParentApplyRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/applications': {
      id: '/parent/applications'
      path: '/applications'
      fullPath: '/parent/applications'
      preLoaderRoute: typeof ParentApplicationsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/marketplace/checkout': {
      id: '/marketplace/checkout'
      path: '/checkout'
      fullPath: '/marketplace/checkout'
      preLoaderRoute: typeof MarketplaceCheckoutRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/cart': {
      id: '/marketplace/cart'
      path: '/cart'
      fullPath: '/marketplace/cart'
      preLoaderRoute: typeof MarketplaceCartRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/logistics/wallet': {
      id: '/logistics/wallet'
      path: '/wallet'
      fullPath: '/logistics/wallet'
      preLoaderRoute: typeof LogisticsWalletRouteImport
      parentRoute: typeof LogisticsRoute
    }
    '/logistics/settings': {
      id: '/logistics/settings'
      path: '/settings'
      fullPath: '/logistics/settings'
      preLoaderRoute: typeof LogisticsSettingsRouteImport
      parentRoute: typeof LogisticsRoute
    }
    '/logistics/routes': {
      id: '/logistics/routes'
      path: '/routes'
      fullPath: '/logistics/routes'
      preLoaderRoute: typeof LogisticsRoutesRouteImport
      parentRoute: typeof LogisticsRoute
    }
    '/logistics/register': {
      id: '/logistics/register'
      path: '/register'
      fullPath: '/logistics/register'
      preLoaderRoute: typeof LogisticsRegisterRouteImport
      parentRoute: typeof LogisticsRoute
    }
    '/logistics/earnings': {
      id: '/logistics/earnings'
      path: '/earnings'
      fullPath: '/logistics/earnings'
      preLoaderRoute: typeof LogisticsEarningsRouteImport
      parentRoute: typeof LogisticsRoute
    }
    '/logistics/deliveries': {
      id: '/logistics/deliveries'
      path: '/deliveries'
      fullPath: '/logistics/deliveries'
      preLoaderRoute: typeof LogisticsDeliveriesRouteImport
      parentRoute: typeof LogisticsRoute
    }
    '/supplier/wallet/deposit': {
      id: '/supplier/wallet/deposit'
      path: '/deposit'
      fullPath: '/supplier/wallet/deposit'
      preLoaderRoute: typeof SupplierWalletDepositRouteImport
      parentRoute: typeof SupplierWalletRoute
    }
    '/supplier/products/new': {
      id: '/supplier/products/new'
      path: '/new'
      fullPath: '/supplier/products/new'
      preLoaderRoute: typeof SupplierProductsNewRouteImport
      parentRoute: typeof SupplierProductsRoute
    }
    '/supplier/orders/$id': {
      id: '/supplier/orders/$id'
      path: '/$id'
      fullPath: '/supplier/orders/$id'
      preLoaderRoute: typeof SupplierOrdersIdRouteImport
      parentRoute: typeof SupplierOrdersRoute
    }
    '/student/wallet/deposit': {
      id: '/student/wallet/deposit'
      path: '/deposit'
      fullPath: '/student/wallet/deposit'
      preLoaderRoute: typeof StudentWalletDepositRouteImport
      parentRoute: typeof StudentWalletRoute
    }
    '/student/scholarships/saved': {
      id: '/student/scholarships/saved'
      path: '/saved'
      fullPath: '/student/scholarships/saved'
      preLoaderRoute: typeof StudentScholarshipsSavedRouteImport
      parentRoute: typeof StudentScholarshipsRoute
    }
    '/student/scholarships/$id': {
      id: '/student/scholarships/$id'
      path: '/$id'
      fullPath: '/student/scholarships/$id'
      preLoaderRoute: typeof StudentScholarshipsIdRouteImport
      parentRoute: typeof StudentScholarshipsRoute
    }
    '/student/orders/$id': {
      id: '/student/orders/$id'
      path: '/$id'
      fullPath: '/student/orders/$id'
      preLoaderRoute: typeof StudentOrdersIdRouteImport
      parentRoute: typeof StudentOrdersRoute
    }
    '/school/wallet/deposit': {
      id: '/school/wallet/deposit'
      path: '/deposit'
      fullPath: '/school/wallet/deposit'
      preLoaderRoute: typeof SchoolWalletDepositRouteImport
      parentRoute: typeof SchoolWalletRoute
    }
    '/school/applications/$id': {
      id: '/school/applications/$id'
      path: '/$id'
      fullPath: '/school/applications/$id'
      preLoaderRoute: typeof SchoolApplicationsIdRouteImport
      parentRoute: typeof SchoolApplicationsRoute
    }
    '/parent/wallet/deposit': {
      id: '/parent/wallet/deposit'
      path: '/deposit'
      fullPath: '/parent/wallet/deposit'
      preLoaderRoute: typeof ParentWalletDepositRouteImport
      parentRoute: typeof ParentWalletRoute
    }
    '/parent/schools/$id': {
      id: '/parent/schools/$id'
      path: '/$id'
      fullPath: '/parent/schools/$id'
      preLoaderRoute: typeof ParentSchoolsIdRouteImport
      parentRoute: typeof ParentSchoolsRoute
    }
    '/parent/scholarships/saved': {
      id: '/parent/scholarships/saved'
      path: '/saved'
      fullPath: '/parent/scholarships/saved'
      preLoaderRoute: typeof ParentScholarshipsSavedRouteImport
      parentRoute: typeof ParentScholarshipsRoute
    }
    '/parent/scholarships/$id': {
      id: '/parent/scholarships/$id'
      path: '/$id'
      fullPath: '/parent/scholarships/$id'
      preLoaderRoute: typeof ParentScholarshipsIdRouteImport
      parentRoute: typeof ParentScholarshipsRoute
    }
    '/parent/receipts/$id': {
      id: '/parent/receipts/$id'
      path: '/$id'
      fullPath: '/parent/receipts/$id'
      preLoaderRoute: typeof ParentReceiptsIdRouteImport
      parentRoute: typeof ParentReceiptsRoute
    }
    '/parent/payments/pay': {
      id: '/parent/payments/pay'
      path: '/pay'
      fullPath: '/parent/payments/pay'
      preLoaderRoute: typeof ParentPaymentsPayRouteImport
      parentRoute: typeof ParentPaymentsRoute
    }
    '/parent/orders/$id': {
      id: '/parent/orders/$id'
      path: '/$id'
      fullPath: '/parent/orders/$id'
      preLoaderRoute: typeof ParentOrdersIdRouteImport
      parentRoute: typeof ParentOrdersRoute
    }
    '/parent/children/new': {
      id: '/parent/children/new'
      path: '/new'
      fullPath: '/parent/children/new'
      preLoaderRoute: typeof ParentChildrenNewRouteImport
      parentRoute: typeof ParentChildrenRoute
    }
    '/parent/children/link': {
      id: '/parent/children/link'
      path: '/link'
      fullPath: '/parent/children/link'
      preLoaderRoute: typeof ParentChildrenLinkRouteImport
      parentRoute: typeof ParentChildrenRoute
    }
    '/parent/children/$id': {
      id: '/parent/children/$id'
      path: '/$id'
      fullPath: '/parent/children/$id'
      preLoaderRoute: typeof ParentChildrenIdRouteImport
      parentRoute: typeof ParentChildrenRoute
    }
    '/parent/applications/$id': {
      id: '/parent/applications/$id'
      path: '/$id'
      fullPath: '/parent/applications/$id'
      preLoaderRoute: typeof ParentApplicationsIdRouteImport
      parentRoute: typeof ParentApplicationsRoute
    }
    '/marketplace/products/$id': {
      id: '/marketplace/products/$id'
      path: '/products/$id'
      fullPath: '/marketplace/products/$id'
      preLoaderRoute: typeof MarketplaceProductsIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/logistics/wallet/deposit': {
      id: '/logistics/wallet/deposit'
      path: '/deposit'
      fullPath: '/logistics/wallet/deposit'
      preLoaderRoute: typeof LogisticsWalletDepositRouteImport
      parentRoute: typeof LogisticsWalletRoute
    }
    '/logistics/deliveries/$id': {
      id: '/logistics/deliveries/$id'
      path: '/$id'
      fullPath: '/logistics/deliveries/$id'
      preLoaderRoute: typeof LogisticsDeliveriesIdRouteImport
      parentRoute: typeof LogisticsDeliveriesRoute
    }
  }
}

interface LogisticsDeliveriesRouteChildren {
  LogisticsDeliveriesIdRoute: typeof LogisticsDeliveriesIdRoute
}

const LogisticsDeliveriesRouteChildren: LogisticsDeliveriesRouteChildren = {
  LogisticsDeliveriesIdRoute: LogisticsDeliveriesIdRoute,
}

const LogisticsDeliveriesRouteWithChildren =
  LogisticsDeliveriesRoute._addFileChildren(LogisticsDeliveriesRouteChildren)

interface LogisticsWalletRouteChildren {
  LogisticsWalletDepositRoute: typeof LogisticsWalletDepositRoute
}

const LogisticsWalletRouteChildren: LogisticsWalletRouteChildren = {
  LogisticsWalletDepositRoute: LogisticsWalletDepositRoute,
}

const LogisticsWalletRouteWithChildren = LogisticsWalletRoute._addFileChildren(
  LogisticsWalletRouteChildren,
)

interface LogisticsRouteChildren {
  LogisticsDeliveriesRoute: typeof LogisticsDeliveriesRouteWithChildren
  LogisticsEarningsRoute: typeof LogisticsEarningsRoute
  LogisticsRegisterRoute: typeof LogisticsRegisterRoute
  LogisticsRoutesRoute: typeof LogisticsRoutesRoute
  LogisticsSettingsRoute: typeof LogisticsSettingsRoute
  LogisticsWalletRoute: typeof LogisticsWalletRouteWithChildren
  LogisticsIndexRoute: typeof LogisticsIndexRoute
}

const LogisticsRouteChildren: LogisticsRouteChildren = {
  LogisticsDeliveriesRoute: LogisticsDeliveriesRouteWithChildren,
  LogisticsEarningsRoute: LogisticsEarningsRoute,
  LogisticsRegisterRoute: LogisticsRegisterRoute,
  LogisticsRoutesRoute: LogisticsRoutesRoute,
  LogisticsSettingsRoute: LogisticsSettingsRoute,
  LogisticsWalletRoute: LogisticsWalletRouteWithChildren,
  LogisticsIndexRoute: LogisticsIndexRoute,
}

const LogisticsRouteWithChildren = LogisticsRoute._addFileChildren(
  LogisticsRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplaceCartRoute: typeof MarketplaceCartRoute
  MarketplaceCheckoutRoute: typeof MarketplaceCheckoutRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  MarketplaceProductsIdRoute: typeof MarketplaceProductsIdRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceCartRoute: MarketplaceCartRoute,
  MarketplaceCheckoutRoute: MarketplaceCheckoutRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  MarketplaceProductsIdRoute: MarketplaceProductsIdRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface ParentApplicationsRouteChildren {
  ParentApplicationsIdRoute: typeof ParentApplicationsIdRoute
}

const ParentApplicationsRouteChildren: ParentApplicationsRouteChildren = {
  ParentApplicationsIdRoute: ParentApplicationsIdRoute,
}

const ParentApplicationsRouteWithChildren =
  ParentApplicationsRoute._addFileChildren(ParentApplicationsRouteChildren)

interface ParentChildrenRouteChildren {
  ParentChildrenIdRoute: typeof ParentChildrenIdRoute
  ParentChildrenLinkRoute: typeof ParentChildrenLinkRoute
  ParentChildrenNewRoute: typeof ParentChildrenNewRoute
}

const ParentChildrenRouteChildren: ParentChildrenRouteChildren = {
  ParentChildrenIdRoute: ParentChildrenIdRoute,
  ParentChildrenLinkRoute: ParentChildrenLinkRoute,
  ParentChildrenNewRoute: ParentChildrenNewRoute,
}

const ParentChildrenRouteWithChildren = ParentChildrenRoute._addFileChildren(
  ParentChildrenRouteChildren,
)

interface ParentOrdersRouteChildren {
  ParentOrdersIdRoute: typeof ParentOrdersIdRoute
}

const ParentOrdersRouteChildren: ParentOrdersRouteChildren = {
  ParentOrdersIdRoute: ParentOrdersIdRoute,
}

const ParentOrdersRouteWithChildren = ParentOrdersRoute._addFileChildren(
  ParentOrdersRouteChildren,
)

interface ParentPaymentsRouteChildren {
  ParentPaymentsPayRoute: typeof ParentPaymentsPayRoute
}

const ParentPaymentsRouteChildren: ParentPaymentsRouteChildren = {
  ParentPaymentsPayRoute: ParentPaymentsPayRoute,
}

const ParentPaymentsRouteWithChildren = ParentPaymentsRoute._addFileChildren(
  ParentPaymentsRouteChildren,
)

interface ParentReceiptsRouteChildren {
  ParentReceiptsIdRoute: typeof ParentReceiptsIdRoute
}

const ParentReceiptsRouteChildren: ParentReceiptsRouteChildren = {
  ParentReceiptsIdRoute: ParentReceiptsIdRoute,
}

const ParentReceiptsRouteWithChildren = ParentReceiptsRoute._addFileChildren(
  ParentReceiptsRouteChildren,
)

interface ParentScholarshipsRouteChildren {
  ParentScholarshipsIdRoute: typeof ParentScholarshipsIdRoute
  ParentScholarshipsSavedRoute: typeof ParentScholarshipsSavedRoute
}

const ParentScholarshipsRouteChildren: ParentScholarshipsRouteChildren = {
  ParentScholarshipsIdRoute: ParentScholarshipsIdRoute,
  ParentScholarshipsSavedRoute: ParentScholarshipsSavedRoute,
}

const ParentScholarshipsRouteWithChildren =
  ParentScholarshipsRoute._addFileChildren(ParentScholarshipsRouteChildren)

interface ParentSchoolsRouteChildren {
  ParentSchoolsIdRoute: typeof ParentSchoolsIdRoute
}

const ParentSchoolsRouteChildren: ParentSchoolsRouteChildren = {
  ParentSchoolsIdRoute: ParentSchoolsIdRoute,
}

const ParentSchoolsRouteWithChildren = ParentSchoolsRoute._addFileChildren(
  ParentSchoolsRouteChildren,
)

interface ParentWalletRouteChildren {
  ParentWalletDepositRoute: typeof ParentWalletDepositRoute
}

const ParentWalletRouteChildren: ParentWalletRouteChildren = {
  ParentWalletDepositRoute: ParentWalletDepositRoute,
}

const ParentWalletRouteWithChildren = ParentWalletRoute._addFileChildren(
  ParentWalletRouteChildren,
)

interface ParentRouteChildren {
  ParentApplicationsRoute: typeof ParentApplicationsRouteWithChildren
  ParentApplyRoute: typeof ParentApplyRoute
  ParentChildrenRoute: typeof ParentChildrenRouteWithChildren
  ParentDocumentsRoute: typeof ParentDocumentsRoute
  ParentFeesRoute: typeof ParentFeesRoute
  ParentNotificationsRoute: typeof ParentNotificationsRoute
  ParentOrdersRoute: typeof ParentOrdersRouteWithChildren
  ParentPaymentsRoute: typeof ParentPaymentsRouteWithChildren
  ParentReceiptsRoute: typeof ParentReceiptsRouteWithChildren
  ParentScholarshipsRoute: typeof ParentScholarshipsRouteWithChildren
  ParentSchoolsRoute: typeof ParentSchoolsRouteWithChildren
  ParentSettingsRoute: typeof ParentSettingsRoute
  ParentUniformsRoute: typeof ParentUniformsRoute
  ParentWalletRoute: typeof ParentWalletRouteWithChildren
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentApplicationsRoute: ParentApplicationsRouteWithChildren,
  ParentApplyRoute: ParentApplyRoute,
  ParentChildrenRoute: ParentChildrenRouteWithChildren,
  ParentDocumentsRoute: ParentDocumentsRoute,
  ParentFeesRoute: ParentFeesRoute,
  ParentNotificationsRoute: ParentNotificationsRoute,
  ParentOrdersRoute: ParentOrdersRouteWithChildren,
  ParentPaymentsRoute: ParentPaymentsRouteWithChildren,
  ParentReceiptsRoute: ParentReceiptsRouteWithChildren,
  ParentScholarshipsRoute: ParentScholarshipsRouteWithChildren,
  ParentSchoolsRoute: ParentSchoolsRouteWithChildren,
  ParentSettingsRoute: ParentSettingsRoute,
  ParentUniformsRoute: ParentUniformsRoute,
  ParentWalletRoute: ParentWalletRouteWithChildren,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface SchoolApplicationsRouteChildren {
  SchoolApplicationsIdRoute: typeof SchoolApplicationsIdRoute
}

const SchoolApplicationsRouteChildren: SchoolApplicationsRouteChildren = {
  SchoolApplicationsIdRoute: SchoolApplicationsIdRoute,
}

const SchoolApplicationsRouteWithChildren =
  SchoolApplicationsRoute._addFileChildren(SchoolApplicationsRouteChildren)

interface SchoolWalletRouteChildren {
  SchoolWalletDepositRoute: typeof SchoolWalletDepositRoute
}

const SchoolWalletRouteChildren: SchoolWalletRouteChildren = {
  SchoolWalletDepositRoute: SchoolWalletDepositRoute,
}

const SchoolWalletRouteWithChildren = SchoolWalletRoute._addFileChildren(
  SchoolWalletRouteChildren,
)

interface SchoolRouteChildren {
  SchoolApplicationsRoute: typeof SchoolApplicationsRouteWithChildren
  SchoolClassesRoute: typeof SchoolClassesRoute
  SchoolFeesRoute: typeof SchoolFeesRoute
  SchoolGalleryRoute: typeof SchoolGalleryRoute
  SchoolOnboardingRoute: typeof SchoolOnboardingRoute
  SchoolPaymentsRoute: typeof SchoolPaymentsRoute
  SchoolPipelineRoute: typeof SchoolPipelineRoute
  SchoolPreviewRoute: typeof SchoolPreviewRoute
  SchoolProfileRoute: typeof SchoolProfileRoute
  SchoolReportsRoute: typeof SchoolReportsRoute
  SchoolRequirementsRoute: typeof SchoolRequirementsRoute
  SchoolSettingsRoute: typeof SchoolSettingsRoute
  SchoolSuppliersRoute: typeof SchoolSuppliersRoute
  SchoolUniformsRoute: typeof SchoolUniformsRoute
  SchoolWalletRoute: typeof SchoolWalletRouteWithChildren
  SchoolIndexRoute: typeof SchoolIndexRoute
}

const SchoolRouteChildren: SchoolRouteChildren = {
  SchoolApplicationsRoute: SchoolApplicationsRouteWithChildren,
  SchoolClassesRoute: SchoolClassesRoute,
  SchoolFeesRoute: SchoolFeesRoute,
  SchoolGalleryRoute: SchoolGalleryRoute,
  SchoolOnboardingRoute: SchoolOnboardingRoute,
  SchoolPaymentsRoute: SchoolPaymentsRoute,
  SchoolPipelineRoute: SchoolPipelineRoute,
  SchoolPreviewRoute: SchoolPreviewRoute,
  SchoolProfileRoute: SchoolProfileRoute,
  SchoolReportsRoute: SchoolReportsRoute,
  SchoolRequirementsRoute: SchoolRequirementsRoute,
  SchoolSettingsRoute: SchoolSettingsRoute,
  SchoolSuppliersRoute: SchoolSuppliersRoute,
  SchoolUniformsRoute: SchoolUniformsRoute,
  SchoolWalletRoute: SchoolWalletRouteWithChildren,
  SchoolIndexRoute: SchoolIndexRoute,
}

const SchoolRouteWithChildren =
  SchoolRoute._addFileChildren(SchoolRouteChildren)

interface SchoolsRouteChildren {
  SchoolsIdRoute: typeof SchoolsIdRoute
  SchoolsIndexRoute: typeof SchoolsIndexRoute
}

const SchoolsRouteChildren: SchoolsRouteChildren = {
  SchoolsIdRoute: SchoolsIdRoute,
  SchoolsIndexRoute: SchoolsIndexRoute,
}

const SchoolsRouteWithChildren =
  SchoolsRoute._addFileChildren(SchoolsRouteChildren)

interface StudentOrdersRouteChildren {
  StudentOrdersIdRoute: typeof StudentOrdersIdRoute
}

const StudentOrdersRouteChildren: StudentOrdersRouteChildren = {
  StudentOrdersIdRoute: StudentOrdersIdRoute,
}

const StudentOrdersRouteWithChildren = StudentOrdersRoute._addFileChildren(
  StudentOrdersRouteChildren,
)

interface StudentScholarshipsRouteChildren {
  StudentScholarshipsIdRoute: typeof StudentScholarshipsIdRoute
  StudentScholarshipsSavedRoute: typeof StudentScholarshipsSavedRoute
}

const StudentScholarshipsRouteChildren: StudentScholarshipsRouteChildren = {
  StudentScholarshipsIdRoute: StudentScholarshipsIdRoute,
  StudentScholarshipsSavedRoute: StudentScholarshipsSavedRoute,
}

const StudentScholarshipsRouteWithChildren =
  StudentScholarshipsRoute._addFileChildren(StudentScholarshipsRouteChildren)

interface StudentWalletRouteChildren {
  StudentWalletDepositRoute: typeof StudentWalletDepositRoute
}

const StudentWalletRouteChildren: StudentWalletRouteChildren = {
  StudentWalletDepositRoute: StudentWalletDepositRoute,
}

const StudentWalletRouteWithChildren = StudentWalletRoute._addFileChildren(
  StudentWalletRouteChildren,
)

interface StudentRouteChildren {
  StudentApplicationsRoute: typeof StudentApplicationsRoute
  StudentDocumentsRoute: typeof StudentDocumentsRoute
  StudentFeesRoute: typeof StudentFeesRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentOrdersRoute: typeof StudentOrdersRouteWithChildren
  StudentPaymentsRoute: typeof StudentPaymentsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentReceiptsRoute: typeof StudentReceiptsRoute
  StudentScholarshipsRoute: typeof StudentScholarshipsRouteWithChildren
  StudentSchoolsRoute: typeof StudentSchoolsRoute
  StudentUniformsRoute: typeof StudentUniformsRoute
  StudentWalletRoute: typeof StudentWalletRouteWithChildren
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentApplicationsRoute: StudentApplicationsRoute,
  StudentDocumentsRoute: StudentDocumentsRoute,
  StudentFeesRoute: StudentFeesRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentOrdersRoute: StudentOrdersRouteWithChildren,
  StudentPaymentsRoute: StudentPaymentsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentReceiptsRoute: StudentReceiptsRoute,
  StudentScholarshipsRoute: StudentScholarshipsRouteWithChildren,
  StudentSchoolsRoute: StudentSchoolsRoute,
  StudentUniformsRoute: StudentUniformsRoute,
  StudentWalletRoute: StudentWalletRouteWithChildren,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface SupplierOrdersRouteChildren {
  SupplierOrdersIdRoute: typeof SupplierOrdersIdRoute
}

const SupplierOrdersRouteChildren: SupplierOrdersRouteChildren = {
  SupplierOrdersIdRoute: SupplierOrdersIdRoute,
}

const SupplierOrdersRouteWithChildren = SupplierOrdersRoute._addFileChildren(
  SupplierOrdersRouteChildren,
)

interface SupplierProductsRouteChildren {
  SupplierProductsNewRoute: typeof SupplierProductsNewRoute
}

const SupplierProductsRouteChildren: SupplierProductsRouteChildren = {
  SupplierProductsNewRoute: SupplierProductsNewRoute,
}

const SupplierProductsRouteWithChildren =
  SupplierProductsRoute._addFileChildren(SupplierProductsRouteChildren)

interface SupplierWalletRouteChildren {
  SupplierWalletDepositRoute: typeof SupplierWalletDepositRoute
}

const SupplierWalletRouteChildren: SupplierWalletRouteChildren = {
  SupplierWalletDepositRoute: SupplierWalletDepositRoute,
}

const SupplierWalletRouteWithChildren = SupplierWalletRoute._addFileChildren(
  SupplierWalletRouteChildren,
)

interface SupplierRouteChildren {
  SupplierInventoryRoute: typeof SupplierInventoryRoute
  SupplierLogisticsRoute: typeof SupplierLogisticsRoute
  SupplierOrdersRoute: typeof SupplierOrdersRouteWithChildren
  SupplierProductsRoute: typeof SupplierProductsRouteWithChildren
  SupplierSalesRoute: typeof SupplierSalesRoute
  SupplierSettingsRoute: typeof SupplierSettingsRoute
  SupplierWalletRoute: typeof SupplierWalletRouteWithChildren
  SupplierIndexRoute: typeof SupplierIndexRoute
}

const SupplierRouteChildren: SupplierRouteChildren = {
  SupplierInventoryRoute: SupplierInventoryRoute,
  SupplierLogisticsRoute: SupplierLogisticsRoute,
  SupplierOrdersRoute: SupplierOrdersRouteWithChildren,
  SupplierProductsRoute: SupplierProductsRouteWithChildren,
  SupplierSalesRoute: SupplierSalesRoute,
  SupplierSettingsRoute: SupplierSettingsRoute,
  SupplierWalletRoute: SupplierWalletRouteWithChildren,
  SupplierIndexRoute: SupplierIndexRoute,
}

const SupplierRouteWithChildren = SupplierRoute._addFileChildren(
  SupplierRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GetStartedRoute: GetStartedRoute,
  LoginRoute: LoginRoute,
  LogisticsRoute: LogisticsRouteWithChildren,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  ParentRoute: ParentRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SchoolRoute: SchoolRouteWithChildren,
  SchoolsRoute: SchoolsRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  SupplierRoute: SupplierRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
